#SPDX-License-Identifier: MIT-0
---
ISO_NAME: debian-13.1.0-amd64-netinst.iso

path_iso_download: "/home/sysadmin/Descargas/{{ ISO_NAME }}"
path_iso: /home/sysadmin/Documentos

SRC_ISO: "/vm/iso/{{ ISO_NAME }}"
OUT_ISO: "/vm/iso/{{ ISO_NAME }}"
MNT_DIR: /vm/iso/debian-iso
WRK_DIR: /vm/iso/debian-iso-work

# defaults file for vms_iso_role
